import { IProduct } from "@/models/productModel";

export const ProductsMockData: IProduct[] = [
    {
        id: 1,
        name: "Modern Sofa",
        description: "Découvrez l'iPhone 16 Pro et laissez-vous séduire par une technologie qui redéfinit les standards. Conçu pour ceux qui exigent le meilleur, ce smartphone premium vous offre une expérience utilisateur incomparable.",
        config3D: { scale: 2.4, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 599.99,
        modelPath: "/models/sofa.glb",
        groundColor: "#8B4513",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0000t8v5h7k9j3m2",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 1,
            name: "Furniture",
        },
    },
    {
        id: 2,
        name: "Wooden Coffee Table",
        description: "Rustic oak coffee table with natural finish",
        config3D: { scale: 1.8, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 249.99,
        modelPath: "/models/coffee_table.glb",
        groundColor: "#4A3728",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0001t8v5h7k9j3m3",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 1,
            name: "Furniture",
        },
    },
    {
        id: 3,
        name: "Ergonomic Chair",
        description: "Adjustable office chair with lumbar support",
        config3D: { scale: 2.0, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 199.99,
        modelPath: "/models/chair.glb",
        groundColor: "#333333",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0002t8v5h7k9j3m4",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 1,
            name: "Furniture",
        },
    },
    {
        id: 4,
        name: "Bookshelf",
        description: "Tall wooden bookshelf with 5 shelves",
        config3D: { scale: 2.5, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 349.99,
        modelPath: "/models/bookshelf.glb",
        groundColor: "#5C4033",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0003t8v5h7k9j3m5",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 1,
            name: "Furniture",
        },
    },
    {
        id: 5,
        name: "Smart TV",
        description: "55-inch 4K OLED smart television",
        config3D: { scale: 2.4, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 999.99,
        modelPath: "/models/tv.glb",
        groundColor: "#000000",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0004t8v5h7k9j3m6",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 2,
            name: "Electronics",
        },
    },
    {
        id: 6,
        name: "Wireless Speaker",
        description: "Portable Bluetooth speaker with 360-degree sound",
        config3D: { scale: 1.2, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 129.99,
        modelPath: "/models/speaker.glb",
        groundColor: "#1C2526",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0005t8v5h7k9j3m7",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 2,
            name: "Electronics",
        },
    },
    {
        id: 7,
        name: "Gaming Console",
        description: "Next-gen gaming console with 1TB storage",
        config3D: { scale: 1.5, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 499.99,
        modelPath: "/models/console.glb",
        groundColor: "#2F4F4F",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0006t8v5h7k9j3m8",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 2,
            name: "Electronics",
        },
    },
    {
        id: 8,
        name: "Laptop Stand",
        description: "Adjustable aluminum laptop stand",
        config3D: { scale: 1.0, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 39.99,
        modelPath: "/models/laptop_stand.glb",
        groundColor: "#C0C0C0",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0007t8v5h7k9j3m9",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 2,
            name: "Electronics",
        },
    },
    {
        id: 9,
        name: "Dining Table",
        description: "6-seater glass dining table",
        config3D: { scale: 2.8, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 799.99,
        modelPath: "/models/dining_table.glb",
        groundColor: "#708090",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0008t8v5h7k9j3n0",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 1,
            name: "Furniture",
        },
    },
    {
        id: 10,
        name: "Desk Lamp",
        description: "LED desk lamp with adjustable brightness",
        config3D: { scale: 1.0, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 49.99,
        modelPath: "/models/desk_lamp.glb",
        groundColor: "#FFD700",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0009t8v5h7k9j3n1",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 3,
            name: "Lighting",
        },
    },
    {
        id: 11,
        name: "Bed Frame",
        description: "Queen-size wooden bed frame",
        config3D: { scale: 3.0, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 699.99,
        modelPath: "/models/bed_frame.glb",
        groundColor: "#3C2F2F",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0010t8v5h7k9j3n2",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 1,
            name: "Furniture",
        },
    },
    {
        id: 12,
        name: "Smart Watch",
        description: "Fitness tracking smartwatch with heart rate monitor",
        config3D: { scale: 0.8, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 199.99,
        modelPath: "/models/smart_watch.glb",
        groundColor: "#1E1E1E",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0011t8v5h7k9j3n3",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 2,
            name: "Electronics",
        },
    },
    {
        id: 13,
        name: "Floor Lamp",
        description: "Modern floor lamp with dimmable light",
        config3D: { scale: 2.2, position: [0, 0, 0], rotation: [0, 0, 0] },
        price: 89.99,
        modelPath: "/models/floor_lamp.glb",
        groundColor: "#B0C4DE",
        createdAt: "2025-07-23T18:58:00Z",
        updatedAt: "2025-07-23T18:58:00Z",
        cuid: "cln0x1a2b0012t8v5h7k9j3n4",
        customisationConfigs: {
            colorCustomisation: [],
            defaultColor: "",
        },
        category: {
            id: 3,
            name: "Lighting",
        },
    },
];
