import type { Metadata } from "next";
import { DM_Mono, Michroma } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/ThemeProvider";
import TanstackProvider from "@/providers/TanstackProvider";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ToastContainer } from "react-toastify";
import { NextAuthProvider } from "@/providers/NextauthProvider";

const DM = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

const michroma = Michroma({
  variable: "--font-michroma",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bienvenue sur Bazzar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${DM.className} ${michroma.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
        >
          <NextAuthProvider>
            <TanstackProvider>
              <NuqsAdapter>
                {children}
              </NuqsAdapter>
              <ToastContainer
                position="bottom-center"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick={false}
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
              />
            </TanstackProvider>
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
